<a href="https://colab.research.google.com/github/psikk/Linear_Algebra_Coding_Projects/blob/main/Worksheet_for_Determinants.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [18]:
# create the matrix:
A = np.matrix([[10, 7],
               [8, 9]])

B = np.matrix([[-10, -1],
               [-4, 7]])

C = np.matrix([[1, -3],
               [7, 7]])


In [12]:
print(A*B)
print(np.linalg.det(A*B))

print(B*A)
print(np.linalg.det(B*A))



[[-128   39]
 [-116   55]]
-2515.999999999999
[[-108  -79]
 [  16   35]]
-2516.0000000000014


In [13]:
print(A*C)
print(np.linalg.det(A*C))

print(C*A)
print(np.linalg.det(C*A))

[[59 19]
 [71 39]]
951.9999999999997
[[-14 -20]
 [126 112]]
951.9999999999997


In [14]:
print(B*C)
print(np.linalg.det(B*C))

print(C*B)
print(np.linalg.det(C*B))

[[-17  23]
 [ 45  61]]
-2071.9999999999995
[[  2 -22]
 [-98  42]]
-2071.9999999999995


In [15]:
print(np.linalg.det(A*B*C))
print(np.linalg.det(A*C*B))
print(np.linalg.det(C*B*A))

-70447.99999999994
-70447.99999999994
-70447.99999999994


In [17]:
# create the matrix:
D = np.matrix([[3, 2, 3],
               [-6, 1, -10],
               [-8, -9, -9]])

E = np.matrix([[1, -2, 1],
               [5, 5, 4],
               [4, 0, 0]])

F = np.matrix([[1, 0, 0],
               [0, 2, 0],
               [-3, -2, 1]])

In [19]:
print(D*E)
print(np.linalg.det(D*E))

print(E*D)
print(np.linalg.det(E*D))

[[ 25   4  11]
 [-41  17  -2]
 [-89 -29 -44]]
3067.9999999999973
[[  7  -9  14]
 [-47 -21 -71]
 [ 12   8  12]]
3067.9999999999973


In [20]:
print(D*F)
print(np.linalg.det(D*F))

print(F*D)
print(np.linalg.det(F*D))

[[ -6  -2   3]
 [ 24  22 -10]
 [ 19   0  -9]]
-118.00000000000004
[[  3   2   3]
 [-12   2 -20]
 [ -5 -17   2]]
-118.00000000000004


In [22]:
print(E*F)
print(np.linalg.det(E*F))

print(F*E)
print(np.linalg.det(F*E))

[[-2 -6  1]
 [-7  2  4]
 [ 4  0  0]]
-103.99999999999999
[[  1  -2   1]
 [ 10  10   8]
 [ -9  -4 -11]]
-104.00000000000007


In [23]:
print(np.linalg.det(D*E*F))
print(np.linalg.det(D*F*E))
print(np.linalg.det(F*E*D))

6135.999999999995
6136.000000000006
6136.000000000006
